Add Unit Test Github Action Workflow
taddyb/t-route pull request #3
Opened 2024-10-11 21:51 UTC by alexju

[Short description explaining the high-level reason for the pull request]

## Additions

- Add Unit Test Run for PR and Push on Master

## Removals

-

## Changes

-

## Testing

1. src/troute-config

## Screenshots

## Notes

-

## Todos

-

## Checklist

- [x ] PR has an informative and human-readable title
- [x ] Changes are limited to a single goal (no scope creep)
- [x ] Code can be automatically merged (no conflicts)
- [x ] Code follows project standards (link if applicable)
- [x ] Passes all existing automated tests
- [x ] Any _change_ in functionality is tested
- [x ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Target Environment support

- [ ] Windows
- [x ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

2024-10-11 21:53 UTC, alexju commented
@taddyb Please review this PR to your development branch.

2024-10-11 22:01 UTC, taddyb requested changes
Thanks for the code additions. Lastly, can you change this file name to:
`troute-tests.yml` to ensure the user knows it's for running tests?

2024-10-11 22:01 UTC, taddyb commented on .github/workflows/ubuntu-unit-test.yml
> +name: T-route Unit Test
Change this to:
`T-Route Pytests`

2024-10-12 05:17 UTC, alexju commented
> Thanks for the code additions. Lastly, can you change this file name to: `troute-tests.yml` to ensure the user knows it's for running tests?

File name changed.

2024-10-15 14:59 UTC, alexju commented
@taddyb can you review this pull request when you get a chance?

2024-11-06 23:33 UTC, closed without merging